// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package parts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "chatpilot/app/internal/app/db"
import "strconv"

func AgentOverview(agent db.Agent) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form hx-put=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("/agent/overview/" + strconv.Itoa(int(agent.Id)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/parts/agent_overview.templ`, Line: 8, Col: 59}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" hx-swap=\"outerHTML\" class=\"space-y-4\" data-editing=\"false\" id=\"agent-form\"><!-- Name --><div class=\"list-item\"><i data-lucide=\"bot-message-square\" class=\"w-6 h-6 text-rose-pine-foam\"></i><div class=\"flex justify-between w-full\"><label class=\"text-sm text-rose-pine-subtle\">Name</label> <input name=\"name\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(agent.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/parts/agent_overview.templ`, Line: 21, Col: 23}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"font-medium text-rose-pine-text bg-transparent text-right\" disabled></div></div><!-- Industry --><div class=\"list-item\"><i data-lucide=\"crosshair\" class=\"w-6 h-6 text-rose-pine-foam\"></i><div class=\"flex justify-between w-full\"><label class=\"text-sm text-rose-pine-subtle\">Industry</label> <input name=\"industry\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(agent.Industry)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/parts/agent_overview.templ`, Line: 34, Col: 27}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" class=\"font-medium text-rose-pine-text bg-transparent text-right\" disabled></div></div><!-- Personality --><div class=\"list-item\"><i data-lucide=\"person-standing\" class=\"w-6 h-6 text-rose-pine-foam\"></i><div class=\"flex justify-between w-full\"><label class=\"text-sm text-rose-pine-subtle\">Personality</label> <input name=\"personality\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(agent.Personality)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/parts/agent_overview.templ`, Line: 47, Col: 30}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" class=\"font-medium text-rose-pine-text bg-transparent text-right\" disabled></div></div><div class=\"list-item\"><i data-lucide=\"plug-zap\" class=\"w-6 h-6 text-rose-pine-foam\"></i><div class=\"flex justify-between w-full\"><label class=\"text-sm text-rose-pine-subtle\">Connected</label><div class=\"font-medium\">Facebook, Zalo</div></div></div><!-- Action Buttons --><div class=\"pt-4 space-x-2\"><button type=\"button\" onclick=\"toggleEdit(true)\" class=\"w-full btn-primary\" id=\"edit-btn\"><div class=\"flex item-centers gap-2 justify-center\"><i data-lucide=\"square-pen\" class=\"\"></i> Edit Details</div></button><div class=\"flex gap-2 justify-end\"><button class=\"btn-primary hidden\" type=\"button\" onclick=\"toggleEdit(false)\" id=\"cancel-btn\">Cancel</button> <button type=\"submit\" class=\"btn-secondary hidden\" id=\"save-btn\">Save</button></div></div></form><script>\n\t\tfunction toggleEdit(editing) {\n\t\t\tconst form = document.getElementById(\"agent-form\");\n\t\t\tform.dataset.editing = editing;\n\n\t\t\t// toggle all inputs\n\t\t\tform.querySelectorAll(\"input\").forEach((input) => {\n\t\t\t\tinput.disabled = !editing;\n\t\t\t\tinput.classList.toggle(\"bg-transparent\", !editing);\n\t\t\t\tinput.classList.toggle(\"bg-rose-pine-base\", editing);\n\t\t\t});\n\n\t\t\t// toggle buttons\n\t\t\tdocument.getElementById(\"edit-btn\").classList.toggle(\"hidden\", editing);\n\t\t\tdocument.getElementById(\"save-btn\").classList.toggle(\"hidden\", !editing);\n\t\t\tdocument.getElementById(\"cancel-btn\").classList.toggle(\"hidden\", !editing);\n\n\t\t\t// optional: reset values on cancel\n\t\t\tif (!editing) {\n\t\t\t\tform.reset();\n\t\t\t}\n\t\t}\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
