// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package part

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BotOverview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-3\"><div class=\"list-item\"><i data-lucide=\"bot-message-square\" class=\"w-[32px] h-[32px] text-rose-pine-foam\"></i><div><div class=\"text-rose-pine-subtle text-sm\">Name</div><div class=\"font-medium text-rose-pine-text\">FashionBot</div></div></div><div class=\"list-item\"><i data-lucide=\"plug-zap\" class=\"w-[32px] h-[32px] text-rose-pine-foam\"></i><div><div class=\"text-rose-pine-subtle text-sm\">Connected to</div><div class=\"font-medium text-rose-pine-text\">Facebook, Instagram</div></div></div><div class=\"list-item\"><i data-lucide=\"crosshair\" class=\"w-[32px] h-[32px] text-rose-pine-foam\"></i><div><div class=\"text-rose-pine-subtle text-sm\">Industry</div><div class=\"font-medium text-rose-pine-text\">Fashion</div></div></div><div class=\"list-item\"><i data-lucide=\"person-standing\" class=\"w-[32px] h-[32px] text-rose-pine-foam\"></i><div><div class=\"text-rose-pine-subtle text-sm\">Personality</div><div class=\"font-medium text-rose-pine-text\">Friendly</div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
